# Configuration file

[audio]
s_rate = 16000
s_len = 64000
frame_size = 1024
hop_size = 512
conv_mod = 'same'

[meta]
json_fname = 'info.json'
save_steps = 40

[neuralnet]
optimizer = 'sgd'
loss = 'mse'
batch_size = 32
epochs = 1