demo:
	@sh demo.sh md=MODE

clean:
	@rm -rf *~ fx/*~ __pycache__ fx/__pycache__

cleanall: clean
	@rm -rf dry fx wet

help:
	@echo "DEMO: make demo [md=[long/slow/fast/quick]]"
	@echo "CLEAN: make clean[all]"
